### ISSUE TITLE
Attachment mismatch 

### ISSUE THREAD

**Issue by CloudRealm** [TaeHagen/bluebubbles-app#20] opened 2024-08-26 14:53 UTC
Not quite how to 100% reproduce this bug. But it seems to happen when there's a lot of attachments being sent. Not clear if the attachment was actually sent or if this is because the images got cached. Also redacted mode was turned on for the second image, the image is actually displayed but when I click on it I get the media page.

![Screenshot_20240826-011215](https://github.com/user-attachments/assets/e1b0f3b4-1492-40de-ab31-275e8151f862)
![Screenshot_20240826-011402](https://github.com/user-attachments/assets/a76868a2-99ad-473d-84f5-9a0353eb136e)

**Comment by TaeHagen** [comment] 2024-11-22 20:38
Duplicate of #38

**Closed as not planned by TaeHagen** 2024-11-22 20:38 UTC
